### ISSUE TITLE
Domain names dataset

### ISSUE THREAD

**Issue by screemix** [stanford-oval/wikidata-emnlp23#2]
First of all, thank you for your work! Really good job. 

However, I have a question. In your paper you mentioned that you used 'instance of' properties.

```Unlike relational databases and Freebase, Wikidata has no predefined domains or types. Any entity can have an arbitrary set of properties. However, even though Wikidata is property-based, all named entities have one or more instance of properties to some domain entity; domain entities are organized into a hierarchy with the subclass of property.```

Could you please share the dataset that divides entities into domains, or at least provide details on obtaining the so-called domains for entities?

**Comment by george1459** [comment]
Hi, thank you for reaching out!

The domain entities exist in Wikidata and named entities are attached to them. We didn't create a dataset to divide entities into domains ourselves.

For example: [Barack Obama](https://www.wikidata.org/wiki/Q76) is an "instance of" [human](https://www.wikidata.org/wiki/Q5), the first relation it has.

You can also reference [this page](https://www.wikidata.org/wiki/Help:Basic_membership_properties) and checkout sections about [instance of (P31)](https://www.wikidata.org/wiki/Property:P31) and [subclass of (P279)](https://www.wikidata.org/wiki/Property:P279) for more information.

During our training process, we convert all domain entities into their names, e.g. in [this example](https://github.com/stanford-oval/wikidata-emnlp23/blob/master/training_data/best.json#L109), the domain entity `wd:written_work` (https://www.wikidata.org/wiki/Q47461344) has been converted from QID to its name.

Let us know if you have further questions!

**Comment by george1459** [comment]
Hey, I will be closing the issue for now. Feel free to re-open it if you have follow-up questions.
