### ISSUE TITLE
Could you please add the data that need to be injected to mongodb?

### ISSUE THREAD

**Issue by NLPerWS** [stanford-oval/wikidata-emnlp23#4]
Could you please add the data that need to be injected into mongodb?
include these:

client = MongoClient("mongodb://localhost:27017/")
webquestion_dev = client["wikidata-eval"]["dev"]
webquestion_test = client["wikidata-eval"]["test"]
qald_test = client["wikidata-eval"]["qald7_test"]
qald_train = client["wikidata-eval"]["qald7_train"]
name_to_pid_mapping = client["wikidata-eval"]["name_to_pid_mapping"]
qid_name_mapping = client["wikidata"]["qid_naming_mapping"]
sparql_results = client["sparql_results"]["sparql_results"]

thank you very much!!

**Comment by george1459** [comment]
Hey! For `webquestion_dev`, simply follow [this](https://github.com/stanford-oval/wikidata-emnlp23/tree/master?tab=readme-ov-file#models--inference),. i.e., just inject `wikidata-emnlp23/WikiWebQuestions/dev.json`, similarly for `webquestion_test`.

If you are not evaluating on `qald-7`, you don't need to input data for those.

The last three are only there for caching purposes, so you don't need to inject data into these dbs.

Are you trying to evaluate another set of predictions on our dev and test set, btw? If so just follow this section: https://github.com/stanford-oval/wikidata-emnlp23/tree/master?tab=readme-ov-file#evaluation (i.e., use `eval_predictions.py`)

**Comment by george1459** [comment]
I am closing this issue for now. Feel free to re-open it if the above does not answer your question!
